# Rust formatting configuration
# See full options at: https://rust-lang.github.io/rustfmt/

# Only using options available in the stable Rust channel

# Indentation (default)
tab_spaces = 4

# Line width
max_width = 100

# Ensure consistent formatting of imports
reorder_imports = true

# Code organization
reorder_modules = true

# Use standard Rust 2021 edition
edition = "2021"

# The following settings are only available in nightly and have been commented out:
# indent_style = "Block"         # Only available in nightly
# imports_layout = "HorizontalVertical"  # Only available in nightly
# imports_granularity = "Crate"  # Only available in nightly
# wrap_comments = true           # Only available in nightly
# comment_width = 100            # Only available in nightly
# format_strings = true          # Only available in nightly
# format_macro_bodies = true     # Only available in nightly
# format_macro_matchers = true   # Only available in nightly